version: "3"
services:
  database:
    image: "mysql"
    volumes:
       - /home/lijing/wiki/db_data:/var/lib/mysql
    restart: always
    environment:
    # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_ROOT_PASSWORD: root

  mediawiki:
    image: mediawiki
    ports:
      - "8080:80"
    links:
      - database
    volumes:
      - /var/www/html/images
      # local/docker
      - /mnt:/mnt
      - /home/lijing/wiki:/var/www/html
    environment:
      MEDIAWIKI_DB_HOST: database
      MEDIAWIKI_DB_NAME: my_wiki
      MEDIAWIKI_DB_PASSWORD: root
